# Generated by Django 5.0.3 on 2025-03-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
